In [1]:
#ravel changes original array, flatten doesnot

In [2]:
import numpy as np

In [11]:
np.random.random((2,2))

array([[0.47489621, 0.36211446],
       [0.65316698, 0.2068202 ]])

In [47]:
np.random.randint(1,10,(5,5))

array([[2, 2, 4, 3, 4],
       [7, 7, 6, 3, 5],
       [9, 6, 6, 4, 8],
       [7, 7, 2, 3, 1],
       [7, 8, 6, 9, 4]])

In [53]:
np.random.random(4)

array([0.85269495, 0.39105022, 0.12316641, 0.25321756])

In [60]:
np.random.randint((2,2))

array([0, 1])

In [62]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [63]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])